version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/Toronto
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: omniauth
    versions:
    - 2.0.2
    - 2.0.3
